- name: backend playbook
  hosts: all
  become: true
  tasks:
    - name: disable nodejs module
      ansible.built.in.shell: dnf module disable nodejs -y
    - name:  enable nodejs modules
      ansible.built.in.shell: dnf module enable nodejs:20 -y
    - name: Install a dnf package
      ansible.built.in.dnf:
        name: nodejs
        state: Present
    - name: Adding User
      ansible.builtin.user:
        name: expense
    - name: Copy service file to remote host
      ansible.builtin.template:
        src: backend.service
        dest: /etc/systemd/system/backend.service
    - name: Import role dependencies
      ansible.builtin.role:
        name: common
        tasks_from: app-preq
    - name: Install nodejs dependencies
      community.general.npm:
        path: "{{app_path}}"
        state: latest
    - name: Install MySQL Client & MySQL Python Module
      ansible.builtin.dnf:
        name:
          - mysql
          - python3-PyMySQL
        state: present
    - name: Load schema
      community.mysql.mysql_db:
        state: import
        name: all
        target: /app/schema/backend.sql
        login_user: root
        login_password: ExpenseApp@1
        login_host: mysql-{{env}}.vikramdevops.tech
    - name: Restart the services
      ansible.built.systemd_services:
        state: restarted
        name: backend
        enabled: true
        daemon_reload: true

