global:
  config_version: 2
input:
  type: file
  path: /var/log/nginx/access.log
  readall: true # Read from the beginning of the file? False means we start at the end of the file and read only new lines.
grok:
  patterns_dir: ./patterns
metrics:
  - type: counter
    name: response_time
    help: Total number of rejected recipients, partitioned by error message.
    match: '%{IP:client_ip}%{SPACE}%{HTTPDATE:time}%{SPACE}%{WORD:http_method}%{SPACE}%{PATH:http_path}%{SPACE}%{WORD}/%{NUMBER:http_version}%{SPACE}%{NUMBER:response_codes}%{SPACE}%{NUMBER:body_size_sent}%{SPACE}%{URI}%{SPACE}%{NUMBER:response_time}'
    labels:
      response_time: '{{.response_time}}'
  - type: counter
    name: response_codes
    help: Total number of rejected recipients, partitioned by error message.
    match: '%{IP:client_ip}%{SPACE}%{HTTPDATE:time}%{SPACE}%{WORD:http_method}%{SPACE}%{PATH:http_path}%{SPACE}%{WORD}/%{NUMBER:http_version}%{SPACE}%{NUMBER:response_codes}%{SPACE}%{NUMBER:body_size_sent}%{SPACE}%{URI}%{SPACE}%{NUMBER:response_time}'
    labels:
      response_codes: '{{.response_codes}}'
server:
  host: 0.0.0.0
  port: 9144
