- name: Create exporter user
  ansible.builtin.user:
    name: prometheus

- name: Download exporter
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1.linux-amd64.tar.gz
    dest: /opt
    remote_src: true
    owner: prometheus
    group: prometheus

- name: Copy Node exporter service file
  ansible.builtin.template:
    src: node-exporter.service
    dest: /etc/systemd/system/node-exporter.service

- name: Start Node exporter service
  ansible.builtin.systemd_service:
    name: node-exporter
    state: restarted
    enabled: yes
    daemon-reload: yes
