- name: Set Prompt
  ansible.builtin.shell: set-prompt {{ component }}-{{ env }}
- name: Setup Node Exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter
- name: Setup nginx Exporter
  ansible.builtin.include_role:
    name: prometheus
    tasks_from: nginx-exporter
  when: install_nginx_exporter
- name: Setup grok Exporter
  ansible.builtin.include_role:
    name: prometheus
    tasks_from: grok-exporter
  when: install_grok_exporter
- name: Install Filebeat
  ansible.builtin.include_role:
    name: filebeat
  when: install_filebeat

- name: Configure rsyslog
  ansible.builtin.include_role:
    name: rsyslog
  when: configure_rsyslog