- name: Set Prompt
  ansible.builtin.shell: set-prompt {{ component }}-{{ env }}
- name: Setup Node Exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter
- name: Setup nginx Exporter
  ansible.builtin.include_role:
    name: prometheus
    tasks_from: nginx-exporter
  when: install_nginx_exporter
